spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pawmates
    username: postgres
    password: 1907
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    user:
      name: ebedi
      password: $2a$10$OUk17yUyYoVVACJ3/xPziOhy7/0gFXIHG1R0gGMgGKkapGO8XkBJ.
