spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pawmates
    username: postgres
    password: 1907
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
      show-sql: true
  security:
    user:
      name: ebedi
      password: $2a$10$OUk17yUyYoVVACJ3/xPziOhy7/0gFXIHG1R0gGMgGKkapGO8XkBJ.
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
